version: '3.8'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    build: .
    volumes:
      - D:\Kurssit\docker\material-applications\simple-web-service\text.log:/usr/src/app/text.log
    container_name: simple-web-service
    command: server
    ports: 
      - 8080:8080