version: '3.8'

services:
  frontend:
      image: frontend
      build: ./example-frontend
      expose:
        - 5000
      ports: 
        - 5000:5000
      networks:
        - nginx-network
     
  backend:
      image: backend
      environment: 
        - REQUEST_ORIGIN=http://localhost
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=bron
        - POSTGRES_PASSWORD=bonton
        - POSTGRES_DATABASE=db_post
      build: ./example-backend
      expose:
        - 8080
      ports: 
        - 8080:8080
      networks: 
        - redis-network
        - db-network
        - nginx-network
      depends_on:
        - db
     
  redis:
      image: redis
      networks: 
        - redis-network
      volumes:
        - ./redis_cache:/data


  db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      volumes:
        - ./database:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: bron
        POSTGRES_PASSWORD: bonton
        POSTGRES_DB: db_post
      container_name: db_postgres
      networks:
        - db-network

  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=http://localhost
      - NGINX_PORT=80
    ports:
      - 80:80
    container_name: nginx
    networks:
      - nginx-network
    depends_on:
      - frontend
      - backend
      
      

networks:
    redis-network:
      name: redis-network
    db-network:
      name: db-network
    nginx-network:
      name: nginx-network
    


